version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install server deps
          command: |
            cd server
            npm ci
      - run:
          name: Run tests
          command: npm test || echo "⚠️ No tests found, skipping..."
      - run:
          name: Build server
          command: |
            cd server
            npx tsc -p . && mkdir -p dist && cp src/schema.sql dist/schema.sql
      - persist_to_workspace:
          root: .
          paths:
            - .

  docker-build-and-push:   # ✅ job name must match exactly
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Show workspace files
          command: |
            pwd
            ls -la
            echo "-----"
            ls -la server || true
            echo "-----"
            [ -f Dockerfile ] && echo "✅ Found Dockerfile at repo root" || echo "❌ Dockerfile missing at repo root"
      - run:
          name: Authenticate with GCP (for Artifact Registry)
          command: |
            echo "$GOOGLE_CREDENTIALS" > ${HOME}/gcp-key.json
            curl -sSL https://sdk.cloud.google.com | bash >/dev/null
            echo 'source "$HOME/google-cloud-sdk/path.bash.inc"' >> $BASH_ENV
            source "$HOME/google-cloud-sdk/path.bash.inc"
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project "$GOOGLE_PROJECT_ID"
            gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev -q
      - run:
          name: Build & Push multi-arch image (linux/amd64)
          command: |
            source "$BASH_ENV"
            IMAGE_URI=${GCP_REGION}-docker.pkg.dev/$GOOGLE_PROJECT_ID/qa-practice-repo/qa-practice-site:latest
            docker buildx create --use --name xbuilder || docker buildx use xbuilder
            docker buildx inspect --bootstrap
            docker buildx build \
              --platform linux/amd64 \
              -t "$IMAGE_URI" \
              -f ./Dockerfile \
              --push \
              .
            echo "IMAGE_URI=$IMAGE_URI" >> $BASH_ENV

  deploy:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup gcloud
          command: |
            echo "$GOOGLE_CREDENTIALS" > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set run/region $GCP_REGION
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy qa-practice-site \
              --image ${GCP_REGION}-docker.pkg.dev/$GOOGLE_PROJECT_ID/qa-practice-repo/qa-practice-site:latest \
              --region $GCP_REGION \
              --platform managed \
              --allow-unauthenticated \
              --add-cloudsql-instances $INSTANCE_CONNECTION_NAME \
              --env-vars-file cloudrun.env.yaml

workflows:
  build_and_deploy:
    jobs:
      - build
      - docker-build-and-push:   # ✅ must match job definition above
          requires:
            - build
      - deploy:
          requires:
            - docker-build-and-push