version: 2.1

orbs:
  node: circleci/node@5.1.0
  gcp-cli: circleci/gcp-cli@2.5.0

jobs:
  build:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install server deps
          command: |
            cd server
            npm ci
      - run:
          name: Install client deps
          command: |
            cd client
            npm ci
      - run:
          name: Build server
          command: |
            cd server
            npm run build
      - run:
          name: Build client
          command: |
            cd client
            npm run build

  deploy:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - checkout
      - run:
          name: Authenticate GCP
          command: |
            echo "$GOOGLE_CREDENTIALS" > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set run/region $GOOGLE_REGION
      - run:
          name: Build & Push Docker image
          command: |
            gcloud builds submit \
              --tag $GOOGLE_REGION-docker.pkg.dev/$GOOGLE_PROJECT_ID/qa-practice-repo/qa-practice-site:latest ./server
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy qa-practice-site \
              --image $GOOGLE_REGION-docker.pkg.dev/$GOOGLE_PROJECT_ID/qa-practice-repo/qa-practice-site:latest \
              --region $GOOGLE_REGION \
              --platform managed \
              --allow-unauthenticated \
              --add-cloudsql-instances $INSTANCE_CONNECTION_NAME \
              --env-vars-file server/cloudrun.env.yaml

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build